import type {
  BillingProfile,
  Contract,
  TimeEntry,
  TravelEntry,
  ExpenseEntry,
  ClientBillingOverride,
} from "./types";

// ============================================================================
// BILLING PROFILES
// ============================================================================
export const mockBillingProfiles: BillingProfile[] = [
  {
    id: "bp_standard",
    name: "Standard MSP",
    description: "Profil de facturation par défaut pour les contrats standards",
    standardRate: 125,
    onsiteRate: 145,
    remoteRate: 125,
    urgentRate: 195,
    afterHoursRate: 175,
    weekendRate: 195,
    travelRate: 95,
    ratePerKm: 0.65,
    travelFlatFee: 0,
    hourBankOverageRate: 145,
    mspExcludedRate: 165,
    minimumBillableMinutes: 15,
    roundingIncrementMinutes: 15,
    billableTimeTypes: [
      "remote_work",
      "onsite_work",
      "travel",
      "preparation",
      "follow_up",
      "other",
    ],
    isDefault: true,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "bp_premium",
    name: "Premium 24/7",
    description: "Pour clients Premium avec couverture étendue",
    standardRate: 165,
    onsiteRate: 185,
    remoteRate: 165,
    urgentRate: 245,
    afterHoursRate: 215,
    weekendRate: 245,
    travelRate: 125,
    ratePerKm: 0.75,
    travelFlatFee: 50,
    hourBankOverageRate: 185,
    mspExcludedRate: 215,
    minimumBillableMinutes: 15,
    roundingIncrementMinutes: 15,
    billableTimeTypes: [
      "remote_work",
      "onsite_work",
      "travel",
      "preparation",
      "follow_up",
      "other",
    ],
    isDefault: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "bp_enterprise",
    name: "Enterprise négocié",
    description: "Tarifs négociés pour grands comptes",
    standardRate: 110,
    onsiteRate: 130,
    remoteRate: 110,
    urgentRate: 175,
    afterHoursRate: 155,
    weekendRate: 175,
    travelRate: 85,
    ratePerKm: 0.55,
    travelFlatFee: 0,
    hourBankOverageRate: 125,
    mspExcludedRate: 145,
    minimumBillableMinutes: 6,
    roundingIncrementMinutes: 6,
    billableTimeTypes: [
      "remote_work",
      "onsite_work",
      "travel",
      "preparation",
      "follow_up",
      "other",
    ],
    isDefault: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
];

// ============================================================================
// CLIENT BILLING OVERRIDES
// ============================================================================
export const mockClientBillingOverrides: ClientBillingOverride[] = [
  {
    id: "cbo_acme",
    organizationId: "org_acme",
    organizationName: "Acme Corp",
    baseProfileId: "bp_standard",
    standardRate: 115, // negotiated
    onsiteRate: 135,
    ratePerKm: 0.75, // higher km rate due to distance
    travelFlatFee: 25,
    notes: "Tarifs négociés depuis janvier 2025 — contrat 3 ans",
    isActive: true,
    effectiveFrom: "2025-01-01T00:00:00Z",
    createdAt: "2024-12-15T00:00:00Z",
    updatedAt: "2024-12-15T00:00:00Z",
  },
  {
    id: "cbo_global",
    organizationId: "org_global",
    organizationName: "Global Finance",
    baseProfileId: "bp_premium",
    standardRate: 175,
    onsiteRate: 205,
    afterHoursRate: 245,
    weekendRate: 275,
    notes: "Premium 24/7 avec tarifs supérieurs négociés",
    isActive: true,
    effectiveFrom: "2025-01-01T00:00:00Z",
    createdAt: "2024-12-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "cbo_techstart",
    organizationId: "org_techstart",
    organizationName: "TechStart Inc",
    baseProfileId: "bp_standard",
    standardRate: 95, // discount startup
    onsiteRate: 115,
    notes: "Tarifs préférentiels startup — révision annuelle",
    isActive: true,
    effectiveFrom: "2025-01-01T00:00:00Z",
    createdAt: "2024-11-20T00:00:00Z",
    updatedAt: "2024-11-20T00:00:00Z",
  },
];

export function getClientBillingOverride(orgId: string): ClientBillingOverride | undefined {
  return mockClientBillingOverrides.find(o => o.organizationId === orgId && o.isActive);
}

// ============================================================================
// CONTRACTS
// ============================================================================
export const mockContracts: Contract[] = [
  {
    id: "contract_acme_msp",
    organizationId: "org_acme",
    organizationName: "Acme Corp",
    name: "Forfait MSP — Acme Corp",
    contractNumber: "MSP-2025-0042",
    type: "msp_monthly",
    status: "active",
    billingProfileId: "bp_standard",
    startDate: "2025-01-01T00:00:00Z",
    endDate: "2025-12-31T23:59:59Z",
    description:
      "Forfait MSP mensuel couvrant le support à distance et sur site pour Acme Corp.",
    mspPlan: {
      monthlyAmount: 4800,
      includedTimeTypes: [
        "remote_work",
        "onsite_work",
        "preparation",
        "follow_up",
        "administration",
      ],
      includesRemoteSupport: true,
      includesOnsiteSupport: true,
      includesTravel: false,
      includesKilometers: false,
      includesUrgent: false,
      includesAfterHours: false,
      includesProjects: false,
      includesRecurringWork: true,
      hasMonthlyCap: true,
      monthlyCapHours: 40,
      excludedCategoryIds: [],
      customExceptions: [
        "Migrations majeures et projets > 8h sont facturés séparément",
        "Achats de matériel facturés en plus",
      ],
    },
    autoRenew: true,
    notes: "Renouvellement automatique annuel",
    createdAt: "2024-12-15T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "contract_techstart_bank",
    organizationId: "org_techstart",
    organizationName: "TechStart Inc",
    name: "Banque d'heures 2025 — TechStart",
    contractNumber: "BNK-2025-0017",
    type: "hour_bank",
    status: "active",
    billingProfileId: "bp_standard",
    startDate: "2025-01-01T00:00:00Z",
    endDate: "2025-12-31T23:59:59Z",
    description: "Banque de 100 heures annuelles pour TechStart Inc.",
    hourBank: {
      totalHoursPurchased: 100,
      hoursConsumed: 67.5,
      eligibleTimeTypes: [
        "remote_work",
        "onsite_work",
        "preparation",
        "follow_up",
      ],
      carryOverHours: false,
      allowOverage: true,
      overageRate: 145,
      includesTravel: false,
      includesOnsite: true,
      validFrom: "2025-01-01T00:00:00Z",
      validTo: "2025-12-31T23:59:59Z",
    },
    autoRenew: false,
    createdAt: "2024-12-20T00:00:00Z",
    updatedAt: "2025-03-15T00:00:00Z",
  },
  {
    id: "contract_global_msp",
    organizationId: "org_global",
    organizationName: "Global Finance",
    name: "Forfait MSP Premium — Global Finance",
    contractNumber: "MSP-2025-0001",
    type: "msp_monthly",
    status: "active",
    billingProfileId: "bp_premium",
    startDate: "2025-01-01T00:00:00Z",
    endDate: "2026-12-31T23:59:59Z",
    description: "Forfait MSP Premium 24/7 pour Global Finance.",
    mspPlan: {
      monthlyAmount: 12500,
      includedTimeTypes: [
        "remote_work",
        "onsite_work",
        "travel",
        "preparation",
        "follow_up",
        "administration",
        "waiting",
      ],
      includesRemoteSupport: true,
      includesOnsiteSupport: true,
      includesTravel: true,
      includesKilometers: true,
      includesUrgent: true,
      includesAfterHours: true,
      includesProjects: false,
      includesRecurringWork: true,
      hasMonthlyCap: false,
      excludedCategoryIds: [],
      customExceptions: ["Projets de développement facturés séparément"],
    },
    autoRenew: true,
    createdAt: "2024-12-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "contract_health_tm",
    organizationId: "org_health",
    organizationName: "HealthCare Plus",
    name: "Temps & Matériel — HealthCare Plus",
    contractNumber: "TM-2025-0023",
    type: "time_and_materials",
    status: "active",
    billingProfileId: "bp_standard",
    startDate: "2025-02-01T00:00:00Z",
    description: "Facturation au temps passé sans engagement",
    autoRenew: false,
    createdAt: "2025-01-25T00:00:00Z",
    updatedAt: "2025-02-01T00:00:00Z",
  },
  {
    id: "contract_media_bank",
    organizationId: "org_media",
    organizationName: "MédiaCentre QC",
    name: "Banque d'heures 50h — MédiaCentre QC",
    contractNumber: "BNK-2025-0031",
    type: "hour_bank",
    status: "active",
    billingProfileId: "bp_standard",
    startDate: "2025-03-01T00:00:00Z",
    endDate: "2026-02-28T23:59:59Z",
    description: "50 heures prépayées valables 12 mois",
    hourBank: {
      totalHoursPurchased: 50,
      hoursConsumed: 48,
      eligibleTimeTypes: [
        "remote_work",
        "onsite_work",
        "preparation",
        "follow_up",
      ],
      carryOverHours: true,
      allowOverage: true,
      overageRate: 135,
      includesTravel: false,
      includesOnsite: true,
      validFrom: "2025-03-01T00:00:00Z",
      validTo: "2026-02-28T23:59:59Z",
    },
    autoRenew: false,
    notes: "Approche du dépassement — 2 h restantes",
    createdAt: "2025-02-20T00:00:00Z",
    updatedAt: "2025-03-30T00:00:00Z",
  },
];

// ============================================================================
// TIME ENTRIES
// ============================================================================

function hoursAgo(h: number): string {
  const d = new Date();
  d.setHours(d.getHours() - h);
  return d.toISOString();
}

function daysAgo(d: number): string {
  const date = new Date();
  date.setDate(date.getDate() - d);
  return date.toISOString();
}

export const mockTimeEntries: TimeEntry[] = [
  {
    id: "te_001",
    ticketId: "t-001",
    ticketNumber: "INC-1042",
    organizationId: "org_acme",
    organizationName: "Acme Corp",
    contractId: "contract_acme_msp",
    agentId: "usr_tech1",
    agentName: "Marie Tremblay",
    timeType: "remote_work",
    startedAt: hoursAgo(3),
    endedAt: hoursAgo(2),
    durationMinutes: 60,
    description: "Diagnostic du problème de connexion VPN sur le poste de l'utilisateur",
    isAfterHours: false,
    isWeekend: false,
    isUrgent: false,
    isOnsite: false,
    coverageStatus: "included_in_contract",
    coverageReason: "Inclus dans le forfait MSP mensuel",
    approvalStatus: "approved",
    createdAt: hoursAgo(2),
    updatedAt: hoursAgo(2),
  },
  {
    id: "te_002",
    ticketId: "t-001",
    ticketNumber: "INC-1042",
    organizationId: "org_acme",
    organizationName: "Acme Corp",
    contractId: "contract_acme_msp",
    agentId: "usr_tech1",
    agentName: "Marie Tremblay",
    timeType: "onsite_work",
    startedAt: hoursAgo(1),
    endedAt: new Date().toISOString(),
    durationMinutes: 60,
    description: "Intervention sur site pour reconfigurer le routeur",
    isAfterHours: false,
    isWeekend: false,
    isUrgent: false,
    isOnsite: true,
    coverageStatus: "included_in_contract",
    coverageReason: "Inclus dans le forfait MSP mensuel",
    approvalStatus: "submitted",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "te_003",
    ticketId: "t-002",
    ticketNumber: "INC-1043",
    organizationId: "org_techstart",
    organizationName: "TechStart Inc",
    contractId: "contract_techstart_bank",
    agentId: "usr_tech2",
    agentName: "Alexandre Dubois",
    timeType: "remote_work",
    startedAt: daysAgo(1),
    endedAt: daysAgo(1),
    durationMinutes: 90,
    description: "Mise à jour de sécurité sur les serveurs Linux",
    isAfterHours: false,
    isWeekend: false,
    isUrgent: false,
    isOnsite: false,
    coverageStatus: "deducted_from_hour_bank",
    coverageReason: "Déduit de la banque d'heures (32.5 h restantes avant déduction)",
    approvalStatus: "approved",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "te_004",
    ticketId: "t-003",
    ticketNumber: "INC-1044",
    organizationId: "org_media",
    organizationName: "MédiaCentre QC",
    contractId: "contract_media_bank",
    agentId: "usr_tech1",
    agentName: "Marie Tremblay",
    timeType: "remote_work",
    startedAt: daysAgo(2),
    endedAt: daysAgo(2),
    durationMinutes: 180,
    description: "Configuration d'un nouvel utilisateur dans Active Directory",
    isAfterHours: false,
    isWeekend: false,
    isUrgent: false,
    isOnsite: false,
    coverageStatus: "hour_bank_overage",
    coverageReason: "2 h déduites de la banque, 1 h facturée en dépassement à 135 $/h",
    hourlyRate: 135,
    amount: 135,
    approvalStatus: "submitted",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: "te_005",
    ticketId: "t-004",
    ticketNumber: "INC-1045",
    organizationId: "org_acme",
    organizationName: "Acme Corp",
    contractId: "contract_acme_msp",
    agentId: "usr_tech2",
    agentName: "Alexandre Dubois",
    timeType: "onsite_work",
    startedAt: daysAgo(3),
    endedAt: daysAgo(3),
    durationMinutes: 120,
    description: "Intervention urgente après-heures suite à une panne réseau",
    isAfterHours: true,
    isWeekend: false,
    isUrgent: true,
    isOnsite: true,
    coverageStatus: "msp_overage",
    coverageReason: "Intervention urgente non incluse dans le forfait MSP",
    hourlyRate: 195,
    amount: 390,
    approvalStatus: "approved",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    id: "te_006",
    ticketId: "t-005",
    ticketNumber: "REQ-2014",
    organizationId: "org_health",
    organizationName: "HealthCare Plus",
    contractId: "contract_health_tm",
    agentId: "usr_tech1",
    agentName: "Marie Tremblay",
    timeType: "remote_work",
    startedAt: daysAgo(4),
    endedAt: daysAgo(4),
    durationMinutes: 45,
    description: "Installation de logiciel sur 3 postes",
    isAfterHours: false,
    isWeekend: false,
    isUrgent: false,
    isOnsite: false,
    coverageStatus: "billable",
    coverageReason: "Contrat Temps & Matériel — facturation au taux applicable",
    hourlyRate: 125,
    amount: 93.75,
    approvalStatus: "draft",
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
  },
];

// ============================================================================
// TRAVEL ENTRIES
// ============================================================================
export const mockTravelEntries: TravelEntry[] = [
  {
    id: "tv_001",
    ticketId: "t-001",
    ticketNumber: "INC-1042",
    organizationId: "org_acme",
    organizationName: "Acme Corp",
    agentId: "usr_tech1",
    agentName: "Marie Tremblay",
    date: hoursAgo(2),
    fromLocation: "Bureau Cetix — Québec",
    toLocation: "Acme Corp — 1234 boul. Laurier",
    distanceKm: 24,
    durationMinutes: 30,
    isRoundTrip: true,
    coverageStatus: "travel_billable",
    coverageReason: "Déplacement non inclus dans le forfait MSP",
    ratePerKm: 0.65,
    flatFee: 0,
    amount: 31.2,
    notes: "Aller-retour pour intervention sur site",
    approvalStatus: "submitted",
    createdAt: hoursAgo(2),
  },
  {
    id: "tv_002",
    ticketId: "t-004",
    ticketNumber: "INC-1045",
    organizationId: "org_acme",
    organizationName: "Acme Corp",
    agentId: "usr_tech2",
    agentName: "Alexandre Dubois",
    date: daysAgo(3),
    fromLocation: "Domicile — Lévis",
    toLocation: "Acme Corp — 1234 boul. Laurier",
    distanceKm: 38,
    durationMinutes: 45,
    isRoundTrip: true,
    coverageStatus: "travel_billable",
    coverageReason: "Déplacement urgent après-heures",
    ratePerKm: 0.65,
    flatFee: 0,
    amount: 49.4,
    approvalStatus: "approved",
    createdAt: daysAgo(3),
  },
  {
    id: "tv_003",
    ticketId: "t-002",
    ticketNumber: "INC-1043",
    organizationId: "org_global",
    organizationName: "Global Finance",
    agentId: "usr_tech1",
    agentName: "Marie Tremblay",
    date: daysAgo(5),
    fromLocation: "Bureau Cetix — Québec",
    toLocation: "Global Finance — Centre-ville",
    distanceKm: 12,
    durationMinutes: 25,
    isRoundTrip: true,
    coverageStatus: "included_in_contract",
    coverageReason: "Déplacement inclus dans le forfait MSP Premium",
    approvalStatus: "approved",
    createdAt: daysAgo(5),
  },
];

// ============================================================================
// EXPENSE ENTRIES
// ============================================================================
export const mockExpenseEntries: ExpenseEntry[] = [
  {
    id: "ex_001",
    ticketId: "t-004",
    ticketNumber: "INC-1045",
    organizationId: "org_acme",
    organizationName: "Acme Corp",
    agentId: "usr_tech2",
    agentName: "Alexandre Dubois",
    date: daysAgo(3),
    expenseType: "meal",
    description: "Souper pendant intervention urgente",
    amount: 24.5,
    isReimbursable: true,
    isRebillable: true,
    hasReceipt: true,
    coverageStatus: "billable",
    coverageReason: "Frais refacturable au client (intervention urgente)",
    approvalStatus: "submitted",
    createdAt: daysAgo(3),
  },
  {
    id: "ex_002",
    ticketId: "t-001",
    ticketNumber: "INC-1042",
    organizationId: "org_acme",
    organizationName: "Acme Corp",
    agentId: "usr_tech1",
    agentName: "Marie Tremblay",
    date: hoursAgo(2),
    expenseType: "parking",
    description: "Stationnement chez Acme",
    amount: 8.0,
    isReimbursable: true,
    isRebillable: true,
    hasReceipt: true,
    coverageStatus: "billable",
    coverageReason: "Frais refacturable",
    approvalStatus: "submitted",
    createdAt: hoursAgo(2),
  },
  {
    id: "ex_003",
    ticketId: "t-005",
    ticketNumber: "REQ-2014",
    organizationId: "org_health",
    organizationName: "HealthCare Plus",
    agentId: "usr_tech1",
    agentName: "Marie Tremblay",
    date: daysAgo(4),
    expenseType: "software",
    description: "Licence Microsoft 365 Business Premium x3",
    amount: 99.0,
    isReimbursable: false,
    isRebillable: true,
    hasReceipt: true,
    coverageStatus: "billable",
    coverageReason: "Achat refacturable au client",
    approvalStatus: "approved",
    createdAt: daysAgo(4),
  },
];
