import type { OrgApprover } from "./types";

export const mockOrgApprovers: OrgApprover[] = [
  // Acme Corp
  {
    id: "appr_001",
    organizationId: "org-2",
    contactId: "ct_robert",
    contactName: "Robert Martin",
    contactEmail: "robert.martin@acme.com",
    contactPhone: "+1 514 555-0210",
    jobTitle: "Directeur TI",
    level: 1,
    isPrimary: true,
    scope: "all_tickets",
    notifyByEmail: true,
    notifyBySms: false,
    isActive: true,
    totalApproved: 47,
    totalRejected: 3,
    averageResponseHours: 2.5,
    createdAt: "2024-09-12T10:00:00Z",
    addedBy: "Jean-Philippe Côté",
  },
  {
    id: "appr_002",
    organizationId: "org-2",
    contactId: "ct_sophie",
    contactName: "Sophie Lavoie",
    contactEmail: "sophie.lavoie@acme.com",
    contactPhone: "+1 514 555-0211",
    jobTitle: "Gestionnaire des opérations",
    level: 2,
    isPrimary: false,
    scope: "high_priority_only",
    notifyByEmail: true,
    notifyBySms: true,
    isActive: true,
    totalApproved: 12,
    totalRejected: 1,
    averageResponseHours: 4.1,
    createdAt: "2024-10-05T14:30:00Z",
    addedBy: "Jean-Philippe Côté",
  },
  // TechStart
  {
    id: "appr_003",
    organizationId: "org-3",
    contactId: "ct_emilie",
    contactName: "Émilie Roy",
    contactEmail: "emilie.roy@techstart.io",
    jobTitle: "CTO",
    level: 1,
    isPrimary: true,
    scope: "all_tickets",
    notifyByEmail: true,
    notifyBySms: false,
    isActive: true,
    totalApproved: 23,
    totalRejected: 0,
    averageResponseHours: 1.8,
    createdAt: "2024-08-01T09:00:00Z",
    addedBy: "Marie Tremblay",
  },
  // Global Finance
  {
    id: "appr_004",
    organizationId: "org-4",
    contactId: "ct_catherine",
    contactName: "Catherine Lemieux",
    contactEmail: "catherine.lemieux@globalfinance.ca",
    contactPhone: "+1 514 555-0410",
    jobTitle: "Vice-présidente TI",
    level: 1,
    isPrimary: true,
    scope: "all_tickets",
    notifyByEmail: true,
    notifyBySms: true,
    isActive: true,
    totalApproved: 89,
    totalRejected: 7,
    averageResponseHours: 3.2,
    createdAt: "2024-06-15T08:00:00Z",
    addedBy: "Jean-Philippe Côté",
  },
  {
    id: "appr_005",
    organizationId: "org-4",
    contactId: "ct_marc",
    contactName: "Marc Bouchard",
    contactEmail: "marc.bouchard@globalfinance.ca",
    jobTitle: "Directeur financier",
    level: 2,
    isPrimary: false,
    scope: "specific_amounts",
    scopeMinAmount: 5000,
    notifyByEmail: true,
    notifyBySms: false,
    isActive: true,
    totalApproved: 14,
    totalRejected: 2,
    averageResponseHours: 8.5,
    createdAt: "2024-07-20T11:00:00Z",
    addedBy: "Jean-Philippe Côté",
  },
];

export function getApproversForOrg(orgId: string): OrgApprover[] {
  return mockOrgApprovers
    .filter((a) => a.organizationId === orgId && a.isActive)
    .sort((a, b) => {
      if (a.isPrimary !== b.isPrimary) return a.isPrimary ? -1 : 1;
      return a.level - b.level;
    });
}
