import type { RecurringTicketTemplate, RecurringRun } from "./recurring-types";
import { computeNextRun } from "./recurring-types";

function daysAgo(d: number): string {
  const date = new Date();
  date.setDate(date.getDate() - d);
  return date.toISOString();
}

export const mockRecurringTemplates: RecurringTicketTemplate[] = [
  {
    id: "rt_001",
    name: "Vérification quotidienne des sauvegardes",
    description:
      "Contrôle quotidien que toutes les jobs Veeam ont terminé sans erreur",
    organizationId: "org-2",
    organizationName: "Acme Corp",
    createdBy: "Jean-Philippe Côté",
    ticketSubject: "[Auto] Vérification des sauvegardes Veeam",
    ticketDescription:
      "Tâche automatique : vérifier l'état des sauvegardes Veeam pour Acme Corp.",
    ticketType: "request",
    ticketPriority: "low",
    ticketUrgency: "low",
    ticketImpact: "low",
    ticketSource: "monitoring",
    defaultAssigneeName: "Marie Tremblay",
    defaultQueueName: "Support général",
    defaultCategory: "Sauvegarde",
    defaultRequesterName: "Système Cetix",
    defaultTags: ["récurrent", "sauvegarde"],
    schedule: {
      frequency: "daily",
      interval: 1,
      startDate: daysAgo(60),
      timeOfDay: "07:00",
    },
    isActive: true,
    lastRunAt: daysAgo(0),
    totalRunsCount: 87,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(0),
  },
  {
    id: "rt_002",
    name: "Maintenance hebdo serveurs (Lun/Mer/Ven)",
    description:
      "Maintenance préventive des serveurs trois fois par semaine en heures creuses",
    organizationId: "org-4",
    organizationName: "Global Finance",
    createdBy: "Jean-Philippe Côté",
    ticketSubject: "[Auto] Maintenance préventive serveurs",
    ticketDescription:
      "Vérification des journaux d'événements, mises à jour Windows en attente, état du RAID, espace disque.",
    ticketType: "request",
    ticketPriority: "medium",
    ticketUrgency: "low",
    ticketImpact: "low",
    ticketSource: "monitoring",
    defaultAssigneeName: "Alexandre Dubois",
    defaultQueueName: "Réseau & Infrastructure",
    defaultCategory: "Maintenance",
    defaultRequesterName: "Système Cetix",
    defaultTags: ["récurrent", "maintenance", "serveurs"],
    schedule: {
      frequency: "weekly",
      interval: 1,
      startDate: daysAgo(180),
      timeOfDay: "06:00",
      daysOfWeek: [1, 3, 5],
    },
    isActive: true,
    lastRunAt: daysAgo(2),
    totalRunsCount: 76,
    createdAt: daysAgo(200),
    updatedAt: daysAgo(2),
  },
  {
    id: "rt_003",
    name: "Audit mensuel des comptes",
    description:
      "Le 1er de chaque mois : revue des comptes utilisateurs, désactivation des inactifs",
    organizationId: "org-5",
    organizationName: "HealthCare Plus",
    createdBy: "Sophie Lavoie",
    ticketSubject: "[Auto] Audit mensuel des comptes utilisateurs",
    ticketDescription:
      "Audit ITIL : exporter la liste AD, vérifier les comptes inactifs > 90 jours, désactiver, remonter le rapport.",
    ticketType: "request",
    ticketPriority: "medium",
    ticketUrgency: "medium",
    ticketImpact: "low",
    ticketSource: "monitoring",
    defaultAssigneeName: "Sophie Lavoie",
    defaultQueueName: "Sécurité",
    defaultCategory: "Audit",
    defaultRequesterName: "Système Cetix",
    defaultTags: ["récurrent", "audit", "comptes"],
    schedule: {
      frequency: "monthly",
      interval: 1,
      startDate: daysAgo(120),
      timeOfDay: "09:00",
      monthlyPattern: "day_of_month",
      dayOfMonth: 1,
    },
    isActive: true,
    lastRunAt: daysAgo(7),
    totalRunsCount: 5,
    createdAt: daysAgo(150),
    updatedAt: daysAgo(7),
  },
  {
    id: "rt_004",
    name: "Rapport SLA hebdomadaire (vendredi PM)",
    description: "Génération automatique du rapport SLA chaque vendredi 17h",
    organizationId: "org-2",
    organizationName: "Acme Corp",
    createdBy: "Jean-Philippe Côté",
    ticketSubject: "[Auto] Rapport SLA hebdomadaire",
    ticketDescription:
      "Générer et envoyer le rapport SLA hebdomadaire au responsable client.",
    ticketType: "request",
    ticketPriority: "low",
    ticketUrgency: "low",
    ticketImpact: "low",
    ticketSource: "monitoring",
    defaultAssigneeName: "Jean-Philippe Côté",
    defaultQueueName: "Support général",
    defaultRequesterName: "Système Cetix",
    defaultTags: ["récurrent", "rapport", "sla"],
    schedule: {
      frequency: "weekly",
      interval: 1,
      startDate: daysAgo(60),
      timeOfDay: "17:00",
      daysOfWeek: [5],
    },
    isActive: true,
    lastRunAt: daysAgo(3),
    totalRunsCount: 8,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(3),
  },
  {
    id: "rt_005",
    name: "Vérification certificats SSL",
    description:
      "Le 15 de chaque mois : vérifier la date d'expiration de tous les certificats SSL",
    organizationId: "org-4",
    organizationName: "Global Finance",
    createdBy: "Alexandre Dubois",
    ticketSubject: "[Auto] Audit certificats SSL",
    ticketDescription:
      "Vérifier les dates d'expiration de tous les certificats SSL et renouveler ceux qui expirent dans < 30 jours.",
    ticketType: "request",
    ticketPriority: "high",
    ticketUrgency: "medium",
    ticketImpact: "high",
    ticketSource: "monitoring",
    defaultAssigneeName: "Alexandre Dubois",
    defaultQueueName: "Sécurité",
    defaultCategory: "Sécurité",
    defaultRequesterName: "Système Cetix",
    defaultTags: ["récurrent", "ssl", "sécurité"],
    schedule: {
      frequency: "monthly",
      interval: 1,
      startDate: daysAgo(90),
      timeOfDay: "10:00",
      monthlyPattern: "day_of_month",
      dayOfMonth: 15,
    },
    isActive: true,
    totalRunsCount: 3,
    createdAt: daysAgo(120),
    updatedAt: daysAgo(15),
  },
  {
    id: "rt_006",
    name: "Test de restauration trimestriel",
    description: "Test de restauration de sauvegarde à chaque trimestre",
    organizationId: "org-3",
    organizationName: "TechStart Inc",
    createdBy: "Marie Tremblay",
    ticketSubject: "[Auto] Test de restauration trimestriel",
    ticketDescription:
      "Effectuer un test de restauration complet d'une VM à partir de la dernière sauvegarde.",
    ticketType: "request",
    ticketPriority: "high",
    ticketUrgency: "medium",
    ticketImpact: "high",
    ticketSource: "monitoring",
    defaultAssigneeName: "Marie Tremblay",
    defaultRequesterName: "Système Cetix",
    defaultTags: ["récurrent", "trimestriel", "dr"],
    schedule: {
      frequency: "monthly",
      interval: 3,
      startDate: daysAgo(80),
      timeOfDay: "14:00",
      monthlyPattern: "day_of_month",
      dayOfMonth: 1,
    },
    isActive: false,
    totalRunsCount: 1,
    createdAt: daysAgo(100),
    updatedAt: daysAgo(80),
  },
];

// Compute nextRunAt for active templates
mockRecurringTemplates.forEach((t) => {
  if (t.isActive) {
    const next = computeNextRun(t.schedule);
    t.nextRunAt = next?.toISOString();
  }
});

// ============================================================================
// RUN HISTORY (last few runs across templates)
// ============================================================================
export const mockRecurringRuns: RecurringRun[] = [
  {
    id: "run_001",
    templateId: "rt_001",
    templateName: "Vérification quotidienne des sauvegardes",
    scheduledFor: daysAgo(0),
    ranAt: daysAgo(0),
    status: "success",
    createdTicketId: "t_auto_8721",
    createdTicketNumber: "TK-8721",
  },
  {
    id: "run_002",
    templateId: "rt_002",
    templateName: "Maintenance hebdo serveurs",
    scheduledFor: daysAgo(2),
    ranAt: daysAgo(2),
    status: "success",
    createdTicketId: "t_auto_8702",
    createdTicketNumber: "TK-8702",
  },
  {
    id: "run_003",
    templateId: "rt_004",
    templateName: "Rapport SLA hebdomadaire",
    scheduledFor: daysAgo(3),
    ranAt: daysAgo(3),
    status: "success",
    createdTicketId: "t_auto_8688",
    createdTicketNumber: "TK-8688",
  },
  {
    id: "run_004",
    templateId: "rt_001",
    templateName: "Vérification quotidienne des sauvegardes",
    scheduledFor: daysAgo(1),
    ranAt: daysAgo(1),
    status: "success",
    createdTicketId: "t_auto_8714",
    createdTicketNumber: "TK-8714",
  },
  {
    id: "run_005",
    templateId: "rt_003",
    templateName: "Audit mensuel des comptes",
    scheduledFor: daysAgo(7),
    ranAt: daysAgo(7),
    status: "success",
    createdTicketId: "t_auto_8612",
    createdTicketNumber: "TK-8612",
  },
];
