import type {
  Project,
  ProjectPhase,
  ProjectMilestone,
  ProjectTask,
  ProjectMember,
  ProjectActivity,
  ClientPortalPermissions,
} from "./types";

function daysFromNow(d: number): string {
  const date = new Date();
  date.setDate(date.getDate() + d);
  return date.toISOString();
}
function daysAgo(d: number): string {
  return daysFromNow(-d);
}

// ============================================================================
// PROJECTS
// ============================================================================
export const mockProjects: Project[] = [
  {
    id: "prj_001",
    code: "PRJ-2025-001",
    name: "Migration Microsoft 365",
    description:
      "Migration complète de l'environnement Exchange 2016 vers Microsoft 365 avec configuration MFA et formation des utilisateurs.",
    organizationId: "org_acme",
    organizationName: "Acme Corp",
    type: "migration",
    status: "active",
    priority: "high",
    managerId: "usr_admin",
    managerName: "Jean-Philippe Côté",
    startDate: daysAgo(45),
    targetEndDate: daysFromNow(30),
    progressPercent: 62,
    budgetHours: 240,
    consumedHours: 148.5,
    budgetAmount: 30000,
    consumedAmount: 18562.5,
    isVisibleToClient: true,
    visibilitySettings: {
      showProject: true,
      showPhases: true,
      showMilestones: true,
      showTasks: true,
      showLinkedTickets: true,
      showTimeConsumed: true,
      showBudgetVsActual: false,
      showInternalNotes: false,
      showActivity: true,
      showTeamMembers: true,
    },
    phaseCount: 5,
    milestoneCount: 4,
    taskCount: 28,
    completedTaskCount: 17,
    linkedTicketCount: 12,
    memberCount: 4,
    tags: ["migration", "office365", "priorité"],
    isAtRisk: false,
    isArchived: false,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(1),
  },
  {
    id: "prj_002",
    code: "PRJ-2025-002",
    name: "Refonte infrastructure réseau",
    description:
      "Remplacement complet des switches et déploiement d'un nouveau pare-feu Fortinet 200F avec segmentation VLAN.",
    organizationId: "org_global",
    organizationName: "Global Finance",
    type: "infrastructure",
    status: "at_risk",
    priority: "critical",
    managerId: "usr_tech1",
    managerName: "Marie Tremblay",
    startDate: daysAgo(60),
    targetEndDate: daysFromNow(7),
    progressPercent: 78,
    budgetHours: 320,
    consumedHours: 285,
    budgetAmount: 48000,
    consumedAmount: 42750,
    isVisibleToClient: true,
    visibilitySettings: {
      showProject: true,
      showPhases: true,
      showMilestones: true,
      showTasks: false,
      showLinkedTickets: true,
      showTimeConsumed: true,
      showBudgetVsActual: true,
      showInternalNotes: false,
      showActivity: true,
      showTeamMembers: true,
    },
    phaseCount: 4,
    milestoneCount: 6,
    taskCount: 42,
    completedTaskCount: 33,
    linkedTicketCount: 18,
    memberCount: 5,
    tags: ["infrastructure", "fortinet", "critique"],
    isAtRisk: true,
    riskNotes:
      "Délai serré, livraison de matériel reportée de 5 jours par le fournisseur",
    isArchived: false,
    createdAt: daysAgo(75),
    updatedAt: daysAgo(0),
  },
  {
    id: "prj_003",
    code: "PRJ-2025-003",
    name: "Implémentation Azure Backup",
    description:
      "Mise en place d'une stratégie de sauvegarde Azure Backup pour les serveurs critiques.",
    organizationId: "org_techstart",
    organizationName: "TechStart Inc",
    type: "implementation",
    status: "planning",
    priority: "medium",
    managerId: "usr_tech2",
    managerName: "Alexandre Dubois",
    startDate: daysFromNow(7),
    targetEndDate: daysFromNow(45),
    progressPercent: 8,
    budgetHours: 80,
    consumedHours: 6,
    budgetAmount: 10000,
    consumedAmount: 750,
    isVisibleToClient: true,
    visibilitySettings: {
      showProject: true,
      showPhases: true,
      showMilestones: true,
      showTasks: true,
      showLinkedTickets: false,
      showTimeConsumed: false,
      showBudgetVsActual: false,
      showInternalNotes: false,
      showActivity: true,
      showTeamMembers: true,
    },
    phaseCount: 3,
    milestoneCount: 3,
    taskCount: 15,
    completedTaskCount: 1,
    linkedTicketCount: 0,
    memberCount: 2,
    tags: ["azure", "backup", "cloud"],
    isAtRisk: false,
    isArchived: false,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(2),
  },
  {
    id: "prj_004",
    code: "PRJ-2025-004",
    name: "Audit de sécurité ISO 27001",
    description:
      "Audit complet de sécurité informatique en préparation à la certification ISO 27001.",
    organizationId: "org_health",
    organizationName: "HealthCare Plus",
    type: "audit",
    status: "active",
    priority: "high",
    managerId: "usr_admin",
    managerName: "Jean-Philippe Côté",
    startDate: daysAgo(20),
    targetEndDate: daysFromNow(60),
    progressPercent: 35,
    budgetHours: 160,
    consumedHours: 56,
    budgetAmount: 24000,
    consumedAmount: 8400,
    isVisibleToClient: true,
    visibilitySettings: {
      showProject: true,
      showPhases: true,
      showMilestones: true,
      showTasks: false,
      showLinkedTickets: false,
      showTimeConsumed: true,
      showBudgetVsActual: false,
      showInternalNotes: false,
      showActivity: false,
      showTeamMembers: false,
    },
    phaseCount: 4,
    milestoneCount: 5,
    taskCount: 22,
    completedTaskCount: 8,
    linkedTicketCount: 4,
    memberCount: 3,
    tags: ["audit", "iso27001", "sécurité"],
    isAtRisk: false,
    isArchived: false,
    createdAt: daysAgo(25),
    updatedAt: daysAgo(0),
  },
  {
    id: "prj_005",
    code: "PRJ-2025-005",
    name: "Déploiement nouvelle agence Acme",
    description:
      "Installation complète du parc informatique pour la nouvelle agence d'Acme à Sherbrooke.",
    organizationId: "org_acme",
    organizationName: "Acme Corp",
    type: "deployment",
    status: "completed",
    priority: "high",
    managerId: "usr_tech1",
    managerName: "Marie Tremblay",
    startDate: daysAgo(120),
    targetEndDate: daysAgo(15),
    actualEndDate: daysAgo(12),
    progressPercent: 100,
    budgetHours: 180,
    consumedHours: 168,
    budgetAmount: 24000,
    consumedAmount: 22400,
    isVisibleToClient: true,
    visibilitySettings: {
      showProject: true,
      showPhases: true,
      showMilestones: true,
      showTasks: true,
      showLinkedTickets: true,
      showTimeConsumed: true,
      showBudgetVsActual: false,
      showInternalNotes: false,
      showActivity: true,
      showTeamMembers: true,
    },
    phaseCount: 4,
    milestoneCount: 4,
    taskCount: 35,
    completedTaskCount: 35,
    linkedTicketCount: 8,
    memberCount: 4,
    tags: ["déploiement", "acme", "succursale"],
    isAtRisk: false,
    isArchived: false,
    createdAt: daysAgo(130),
    updatedAt: daysAgo(12),
  },
  {
    id: "prj_006",
    code: "PRJ-2025-006",
    name: "Refactor SharePoint MédiaCentre",
    description:
      "Réorganisation complète de la structure SharePoint et migration des bibliothèques.",
    organizationId: "org_media",
    organizationName: "MédiaCentre QC",
    type: "consulting",
    status: "on_hold",
    priority: "low",
    managerId: "usr_tech2",
    managerName: "Alexandre Dubois",
    startDate: daysAgo(30),
    targetEndDate: daysFromNow(90),
    progressPercent: 22,
    budgetHours: 100,
    consumedHours: 22,
    budgetAmount: 13000,
    consumedAmount: 2750,
    isVisibleToClient: false,
    visibilitySettings: {
      showProject: false,
      showPhases: false,
      showMilestones: false,
      showTasks: false,
      showLinkedTickets: false,
      showTimeConsumed: false,
      showBudgetVsActual: false,
      showInternalNotes: false,
      showActivity: false,
      showTeamMembers: false,
    },
    phaseCount: 3,
    milestoneCount: 2,
    taskCount: 12,
    completedTaskCount: 3,
    linkedTicketCount: 5,
    memberCount: 2,
    tags: ["sharepoint", "consulting"],
    isAtRisk: false,
    riskNotes: "En attente de retour client sur la nouvelle structure",
    isArchived: false,
    createdAt: daysAgo(40),
    updatedAt: daysAgo(8),
  },
  {
    id: "prj_007",
    code: "PRJ-2025-007",
    name: "Mise à jour Windows Server 2025",
    description:
      "Mise à niveau de tous les serveurs Windows vers la version 2025.",
    organizationId: "org_global",
    organizationName: "Global Finance",
    type: "upgrade",
    status: "draft",
    priority: "medium",
    managerId: "usr_tech1",
    managerName: "Marie Tremblay",
    startDate: daysFromNow(30),
    targetEndDate: daysFromNow(120),
    progressPercent: 0,
    budgetHours: 200,
    consumedHours: 0,
    budgetAmount: 28000,
    consumedAmount: 0,
    isVisibleToClient: false,
    visibilitySettings: {
      showProject: false,
      showPhases: false,
      showMilestones: false,
      showTasks: false,
      showLinkedTickets: false,
      showTimeConsumed: false,
      showBudgetVsActual: false,
      showInternalNotes: false,
      showActivity: false,
      showTeamMembers: false,
    },
    phaseCount: 0,
    milestoneCount: 0,
    taskCount: 0,
    completedTaskCount: 0,
    linkedTicketCount: 0,
    memberCount: 1,
    tags: ["windows", "serveur"],
    isAtRisk: false,
    isArchived: false,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
];

// ============================================================================
// PHASES (for prj_001)
// ============================================================================
export const mockProjectPhases: ProjectPhase[] = [
  {
    id: "ph_001",
    projectId: "prj_001",
    name: "Préparation et planification",
    description: "Inventaire, planification de la migration, communication aux utilisateurs",
    order: 1,
    status: "completed",
    progressPercent: 100,
    startDate: daysAgo(45),
    endDate: daysAgo(30),
    isVisibleToClient: true,
    taskIds: ["tsk_001", "tsk_002", "tsk_003"],
    milestoneIds: ["ms_001"],
  },
  {
    id: "ph_002",
    projectId: "prj_001",
    name: "Configuration tenant Microsoft 365",
    description: "Configuration du tenant, domaines, DNS, MFA",
    order: 2,
    status: "completed",
    progressPercent: 100,
    startDate: daysAgo(30),
    endDate: daysAgo(20),
    isVisibleToClient: true,
    taskIds: ["tsk_004", "tsk_005"],
    milestoneIds: ["ms_002"],
  },
  {
    id: "ph_003",
    projectId: "prj_001",
    name: "Migration des boîtes courriel",
    description: "Migration progressive des boîtes par groupes d'utilisateurs",
    order: 3,
    status: "in_progress",
    progressPercent: 65,
    startDate: daysAgo(20),
    endDate: daysFromNow(7),
    isVisibleToClient: true,
    taskIds: ["tsk_006", "tsk_007", "tsk_008"],
    milestoneIds: ["ms_003"],
  },
  {
    id: "ph_004",
    projectId: "prj_001",
    name: "Formation et adoption",
    description: "Sessions de formation pour les utilisateurs et les responsables",
    order: 4,
    status: "not_started",
    progressPercent: 0,
    startDate: daysFromNow(7),
    endDate: daysFromNow(20),
    isVisibleToClient: true,
    taskIds: [],
    milestoneIds: [],
  },
  {
    id: "ph_005",
    projectId: "prj_001",
    name: "Décommissionnement Exchange",
    description: "Mise hors service du serveur Exchange 2016",
    order: 5,
    status: "not_started",
    progressPercent: 0,
    startDate: daysFromNow(20),
    endDate: daysFromNow(30),
    isVisibleToClient: true,
    taskIds: [],
    milestoneIds: ["ms_004"],
  },
];

// ============================================================================
// MILESTONES (for prj_001)
// ============================================================================
export const mockProjectMilestones: ProjectMilestone[] = [
  {
    id: "ms_001",
    projectId: "prj_001",
    phaseId: "ph_001",
    name: "Plan de migration approuvé",
    description: "Plan formel approuvé par le client",
    targetDate: daysAgo(35),
    achievedDate: daysAgo(33),
    status: "achieved",
    isVisibleToClient: true,
    isCriticalPath: true,
  },
  {
    id: "ms_002",
    projectId: "prj_001",
    phaseId: "ph_002",
    name: "Tenant M365 prêt",
    description: "Tenant configuré avec sécurité et MFA",
    targetDate: daysAgo(22),
    achievedDate: daysAgo(20),
    status: "achieved",
    isVisibleToClient: true,
    isCriticalPath: true,
  },
  {
    id: "ms_003",
    projectId: "prj_001",
    phaseId: "ph_003",
    name: "50% des boîtes migrées",
    description: "Première moitié des boîtes courriel migrées",
    targetDate: daysAgo(3),
    achievedDate: daysAgo(2),
    status: "achieved",
    isVisibleToClient: true,
    isCriticalPath: false,
  },
  {
    id: "ms_004",
    projectId: "prj_001",
    phaseId: "ph_005",
    name: "Migration complète",
    description: "Toutes les boîtes migrées et Exchange décommissionné",
    targetDate: daysFromNow(28),
    status: "upcoming",
    isVisibleToClient: true,
    isCriticalPath: true,
  },
];

// ============================================================================
// TASKS (for prj_001)
// ============================================================================
export const mockProjectTasks: ProjectTask[] = [
  {
    id: "tsk_001",
    projectId: "prj_001",
    phaseId: "ph_001",
    name: "Inventaire des comptes courriel",
    description: "Recenser tous les comptes existants et leurs configurations",
    status: "completed",
    priority: "high",
    assigneeId: "usr_tech1",
    assigneeName: "Marie Tremblay",
    startDate: daysAgo(45),
    dueDate: daysAgo(40),
    completedAt: daysAgo(40),
    estimatedHours: 8,
    actualHours: 7.5,
    progressPercent: 100,
    isVisibleToClient: true,
    dependsOn: [],
    order: 1,
  },
  {
    id: "tsk_002",
    projectId: "prj_001",
    phaseId: "ph_001",
    name: "Plan de communication aux utilisateurs",
    description: "Préparation du courriel d'annonce et FAQ",
    status: "completed",
    priority: "medium",
    assigneeId: "usr_admin",
    assigneeName: "Jean-Philippe Côté",
    startDate: daysAgo(40),
    dueDate: daysAgo(38),
    completedAt: daysAgo(38),
    estimatedHours: 4,
    actualHours: 3.5,
    progressPercent: 100,
    isVisibleToClient: true,
    dependsOn: ["tsk_001"],
    order: 2,
  },
  {
    id: "tsk_003",
    projectId: "prj_001",
    phaseId: "ph_001",
    name: "Validation du plan avec le client",
    description: "Réunion de validation du plan de migration",
    status: "completed",
    priority: "critical",
    assigneeId: "usr_admin",
    assigneeName: "Jean-Philippe Côté",
    startDate: daysAgo(38),
    dueDate: daysAgo(35),
    completedAt: daysAgo(33),
    estimatedHours: 2,
    actualHours: 2.5,
    progressPercent: 100,
    isVisibleToClient: true,
    dependsOn: ["tsk_002"],
    order: 3,
  },
  {
    id: "tsk_004",
    projectId: "prj_001",
    phaseId: "ph_002",
    name: "Création du tenant Microsoft 365",
    description: "Achat des licences et configuration initiale du tenant",
    status: "completed",
    priority: "high",
    assigneeId: "usr_tech1",
    assigneeName: "Marie Tremblay",
    startDate: daysAgo(30),
    dueDate: daysAgo(28),
    completedAt: daysAgo(27),
    estimatedHours: 6,
    actualHours: 7,
    progressPercent: 100,
    isVisibleToClient: true,
    dependsOn: ["tsk_003"],
    order: 4,
  },
  {
    id: "tsk_005",
    projectId: "prj_001",
    phaseId: "ph_002",
    name: "Configuration MFA et politiques de sécurité",
    description: "Mise en place du MFA pour tous les comptes admin",
    status: "completed",
    priority: "critical",
    assigneeId: "usr_tech2",
    assigneeName: "Alexandre Dubois",
    startDate: daysAgo(27),
    dueDate: daysAgo(22),
    completedAt: daysAgo(20),
    estimatedHours: 12,
    actualHours: 14,
    progressPercent: 100,
    isVisibleToClient: true,
    dependsOn: ["tsk_004"],
    order: 5,
  },
  {
    id: "tsk_006",
    projectId: "prj_001",
    phaseId: "ph_003",
    name: "Migration vague 1 (10 utilisateurs pilotes)",
    description: "Migration du premier groupe d'utilisateurs",
    status: "completed",
    priority: "high",
    assigneeId: "usr_tech1",
    assigneeName: "Marie Tremblay",
    startDate: daysAgo(20),
    dueDate: daysAgo(15),
    completedAt: daysAgo(14),
    estimatedHours: 16,
    actualHours: 18,
    progressPercent: 100,
    isVisibleToClient: true,
    dependsOn: ["tsk_005"],
    order: 6,
  },
  {
    id: "tsk_007",
    projectId: "prj_001",
    phaseId: "ph_003",
    name: "Migration vague 2 (50 utilisateurs)",
    description: "Migration du gros du parc",
    status: "in_progress",
    priority: "high",
    assigneeId: "usr_tech2",
    assigneeName: "Alexandre Dubois",
    startDate: daysAgo(14),
    dueDate: daysFromNow(2),
    estimatedHours: 40,
    actualHours: 28,
    progressPercent: 65,
    isVisibleToClient: true,
    dependsOn: ["tsk_006"],
    order: 7,
  },
  {
    id: "tsk_008",
    projectId: "prj_001",
    phaseId: "ph_003",
    name: "Migration vague 3 (utilisateurs restants)",
    description: "Dernière vague avec les boîtes partagées",
    status: "todo",
    priority: "medium",
    assigneeId: "usr_tech1",
    assigneeName: "Marie Tremblay",
    startDate: daysFromNow(2),
    dueDate: daysFromNow(7),
    estimatedHours: 24,
    actualHours: 0,
    progressPercent: 0,
    isVisibleToClient: true,
    dependsOn: ["tsk_007"],
    order: 8,
  },
];

// ============================================================================
// MEMBERS (for prj_001)
// ============================================================================
export const mockProjectMembers: ProjectMember[] = [
  {
    id: "pm_001",
    projectId: "prj_001",
    agentId: "usr_admin",
    agentName: "Jean-Philippe Côté",
    agentEmail: "jp.cote@cetix.ca",
    role: "project_manager",
    allocatedHoursPerWeek: 10,
  },
  {
    id: "pm_002",
    projectId: "prj_001",
    agentId: "usr_tech1",
    agentName: "Marie Tremblay",
    agentEmail: "marie@cetix.ca",
    role: "lead",
    allocatedHoursPerWeek: 20,
  },
  {
    id: "pm_003",
    projectId: "prj_001",
    agentId: "usr_tech2",
    agentName: "Alexandre Dubois",
    agentEmail: "alex@cetix.ca",
    role: "contributor",
    allocatedHoursPerWeek: 15,
  },
  {
    id: "pm_004",
    projectId: "prj_001",
    agentId: "usr_supervisor",
    agentName: "Sophie Lavoie",
    agentEmail: "sophie@cetix.ca",
    role: "reviewer",
    allocatedHoursPerWeek: 5,
  },
];

// ============================================================================
// ACTIVITIES (for prj_001)
// ============================================================================
export const mockProjectActivities: ProjectActivity[] = [
  {
    id: "act_001",
    projectId: "prj_001",
    type: "task_completed",
    authorName: "Marie Tremblay",
    content: "A terminé la tâche « Migration vague 1 (10 utilisateurs pilotes) »",
    isVisibleToClient: true,
    createdAt: daysAgo(14),
  },
  {
    id: "act_002",
    projectId: "prj_001",
    type: "milestone_achieved",
    authorName: "Système",
    content: "Jalon atteint : « 50% des boîtes migrées »",
    isVisibleToClient: true,
    createdAt: daysAgo(2),
  },
  {
    id: "act_003",
    projectId: "prj_001",
    type: "comment",
    authorName: "Alexandre Dubois",
    content:
      "Migration de la vague 2 en cours, environ 65% complétée. Aucun incident majeur à signaler.",
    isVisibleToClient: true,
    createdAt: daysAgo(1),
  },
  {
    id: "act_004",
    projectId: "prj_001",
    type: "ticket_linked",
    authorName: "Jean-Philippe Côté",
    content: "A lié le ticket INC-1042 au projet",
    isVisibleToClient: false,
    createdAt: daysAgo(3),
  },
];

// ============================================================================
// CLIENT PORTAL PERMISSIONS
// ============================================================================
export const mockClientPortalPermissions: ClientPortalPermissions[] = [
  {
    contactId: "ct_001",
    organizationId: "org_acme",
    canAccessPortal: true,
    canSeeOwnTickets: true,
    canSeeAllOrganizationTickets: true,
    canCreateTickets: true,
    canSeeProjects: true,
    canSeeProjectDetails: true,
    canSeeProjectTasks: true,
    canSeeProjectLinkedTickets: true,
    canSeeReports: true,
    canSeeBillingReports: true,
    canSeeTimeReports: true,
    canSeeHourBankBalance: true,
    canSeeDocuments: true,
    canSeeTeamMembers: true,
    portalRole: "admin",
  },
  {
    contactId: "ct_002",
    organizationId: "org_acme",
    canAccessPortal: true,
    canSeeOwnTickets: true,
    canSeeAllOrganizationTickets: true,
    canCreateTickets: true,
    canSeeProjects: true,
    canSeeProjectDetails: true,
    canSeeProjectTasks: true,
    canSeeProjectLinkedTickets: true,
    canSeeReports: true,
    canSeeBillingReports: false,
    canSeeTimeReports: true,
    canSeeHourBankBalance: true,
    canSeeDocuments: true,
    canSeeTeamMembers: true,
    portalRole: "manager",
  },
  {
    contactId: "ct_003",
    organizationId: "org_acme",
    canAccessPortal: true,
    canSeeOwnTickets: true,
    canSeeAllOrganizationTickets: false,
    canCreateTickets: true,
    canSeeProjects: false,
    canSeeProjectDetails: false,
    canSeeProjectTasks: false,
    canSeeProjectLinkedTickets: false,
    canSeeReports: false,
    canSeeBillingReports: false,
    canSeeTimeReports: false,
    canSeeHourBankBalance: false,
    canSeeDocuments: false,
    canSeeTeamMembers: false,
    portalRole: "viewer",
  },
];
